// Bounded independent receiving check against frozen generated bytes only.
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const {chromium} = require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root = __dirname;
const docs = '/dev/shm/portfolio-screenshot-access-dc13ebf4687f/docs';
const output = path.join(root, 'browser');
const sha = value => crypto.createHash('sha256').update(value).digest('hex');

async function main() {
  fs.mkdirSync(output);
  const staticReceipt = JSON.parse(fs.readFileSync(path.join(root, 'static-receipt.json')));
  const record = JSON.parse(fs.readFileSync(path.join(docs, 'cv.json')));
  const expected = staticReceipt.candidate_screenshot_links;
  const inventory = () => staticReceipt.build.exact_generated_files.map(row => {
    const bytes = fs.readFileSync(path.join(docs, row.path));
    assert.equal(sha(bytes), row.sha256, row.path);
    return {path:row.path, bytes:bytes.length, sha256:sha(bytes)};
  });
  const before = inventory();
  const result = {candidate:staticReceipt.candidate, docs, program_sha256:sha(fs.readFileSync(__filename)),
    node:process.version, playwright:require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json').version,
    source_before:before, served:[], blocked:[], viewports:[], native_navigations:[], page_errors:[]};
  const server = http.createServer((req, res) => {
    const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
    const relative = pathname.replace(/^\/preview\//, '/').replace(/^\//, '') || 'index.html';
    const file = path.resolve(docs, relative);
    if (!file.startsWith(path.resolve(docs) + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) {
      res.writeHead(404); res.end(); return;
    }
    const bytes = fs.readFileSync(file);
    const type = {'.html':'text/html', '.css':'text/css', '.webp':'image/webp', '.svg':'image/svg+xml', '.png':'image/png', '.ico':'image/x-icon'}[path.extname(file)] || 'application/octet-stream';
    result.served.push({path:pathname, bytes:bytes.length, sha256:sha(bytes), type});
    res.writeHead(200, {'Content-Type':type}); res.end(bytes);
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  let browser, page;
  try {
    browser = await chromium.launch({executablePath:'/workspace/scratch/ae0a1ea0b247/browser-tools/runtime/chromium',
      headless:true, timeout:10000, args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});
    result.browser = browser.version();
    const context = await browser.newContext({viewport:{width:1280,height:900}, reducedMotion:'reduce'});
    await context.route('**/*', route => {
      if (new URL(route.request().url()).origin === origin) return route.continue();
      result.blocked.push(route.request().url()); return route.abort();
    });
    for (const width of [1280, 390]) {
      page = await context.newPage();
      page.setDefaultTimeout(5000);
      page.setDefaultNavigationTimeout(5000);
      await page.setViewportSize({width,height:900});
      page.on('pageerror', error => result.page_errors.push(String(error)));
      const prefix = width === 390 ? '/preview/' : '/';
      await page.goto(origin + prefix + 'index.html', {waitUntil:'load'});
      await page.locator('img').evaluateAll(images => images.forEach(img => img.loading = 'eager'));
      const row = {width, entry:prefix + 'index.html', tab_sequences:[]};
      result.viewports.push(row);
      row.pre_decode_images = await page.locator('img').evaluateAll(images => images.map(img => ({src:img.getAttribute('src'),complete:img.complete,width:img.naturalWidth,height:img.naturalHeight})));
      await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth), {timeout:5000});
      row.images_decoded = true;
      assert.equal(await page.locator('.screenshot-link').count(), 6);
      assert.equal(await page.locator('.demo img').count(), 6);
      row.no_horizontal_overflow = await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
      assert.equal(row.no_horizontal_overflow, true);
      for (const demo of record.demos) {
        await page.locator(`#demo-${demo.id} summary`).focus();
        const sequence = [];
        for (const device of ['desktop', 'phone']) {
          await page.keyboard.press('Tab');
          const focus = await page.evaluate(() => {
            const el = document.activeElement, box = el.getBoundingClientRect(), style = getComputedStyle(el);
            return {name:el.getAttribute('aria-label'), href:el.getAttribute('href'), visible:el.matches(':focus-visible'),
              outline:style.outlineWidth, height:box.height, x:box.x, right:box.right, viewport:innerWidth};
          });
          assert.equal(focus.name, `${demo.name}: full ${device} screenshot`);
          assert.equal(focus.visible, true); assert.equal(focus.outline, '2px');
          assert.ok(focus.height >= 44 && focus.x >= 0 && focus.right <= focus.viewport);
          sequence.push(focus);
        }
        await page.keyboard.press('Tab');
        assert.equal(await page.evaluate(() => document.activeElement.getAttribute('href')), demo.play.url);
        row.tab_sequences.push({demo:demo.name, links:sequence, next:demo.play.url});
      }
      await page.locator('#demo-returnby').screenshot({path:path.join(output, `returnby-${width}.png`), timeout:5000});
      if (width === 390) {
        for (const shot of expected) {
          const link = page.getByRole('link', {name:shot.label, exact:true});
          await link.focus();
          const [response] = await Promise.all([page.waitForNavigation({waitUntil:'load'}), page.keyboard.press('Enter')]);
          const raw = await response.body();
          const observation = {name:shot.label, url:page.url(), status:response.status(), bytes:raw.length, sha256:sha(raw)};
          result.native_navigations.push(observation);
          assert.equal(observation.url, origin + prefix + shot.href);
          assert.equal(observation.status, 200);
          assert.equal(observation.sha256, shot.sha256);
          await page.waitForFunction(() => document.images.length === 1 && document.images[0].complete && document.images[0].naturalWidth, {timeout:5000});
          observation.dimensions = await page.locator('img').evaluate(img => ({width:img.naturalWidth,height:img.naturalHeight}));
          assert.deepEqual(observation.dimensions, {width:shot.width,height:shot.height});
          await page.goBack({waitUntil:'load'});
          assert.equal(page.url(), origin + prefix + 'index.html');
        }
      }
      await page.close(); page = undefined;
    }
    assert.deepEqual(result.blocked, []);
    assert.deepEqual(result.page_errors, []);
    result.ok = true;
  } catch (error) {
    result.ok = false; result.error = String(error.stack || error); process.exitCode = 1;
    if (page) try {
      result.images_at_failure = await page.locator('img').evaluateAll(images => images.map(img => ({src:img.getAttribute('src'),complete:img.complete,width:img.naturalWidth,height:img.naturalHeight})));
    } catch (diagnostic) { result.diagnostic_error = String(diagnostic); }
  } finally {
    if (browser) await browser.close();
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
  }
  result.source_after = inventory();
  assert.deepEqual(result.source_after, before);
  fs.writeFileSync(path.join(output, 'receipt.json'), JSON.stringify(result,null,2) + '\n');
  console.log(JSON.stringify({ok:result.ok,browser:result.browser,viewports:result.viewports.map(r=>({width:r.width,images_decoded:r.images_decoded,no_horizontal_overflow:r.no_horizontal_overflow})),navigations:result.native_navigations.length,error:result.error}));
}
main().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
