#!/usr/bin/env python3
"""Build Jacob Metoyer's public academic/research site from an explicit allowlist."""
from __future__ import annotations
import argparse, hashlib, html, json, re, shutil
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parent
BASE = 'https://jacobmetoyer.com'
STAMP = '2026-09-29'
NAV = [('work.html','Work'),('research.html','Academic research'),('ai-systems.html','AI systems'),('computing.html','Software'),('making.html','Making'),('collaborate.html','Collaborate'),('about.html','About')]
ALLOWED_HOSTS = {'github.com','www.instagram.com','myanimelist.net','www.linkedin.com','www.csulbtbp.org'}
E = html.escape
# W-12: GitHub Pages cannot send headers, so the policy ships as a meta tag. Every resource is
# same-origin; the JSON-LD block is a data block and is never executed, so it needs no allowance.
# Deliberately no upgrade-insecure-requests until HTTPS works on the custom domain (W-01).
# frame-ancestors/report-uri/sandbox are ignored in meta, so they are not claimed here.
CSP = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; base-uri 'none'; form-action 'none'"
# W-10: raster icons for crawlers/iOS that ignore the SVG icon, plus a 1200x630 share card.
# Generated by make_images.py from the mark.svg palette and committed; the build only copies them.
ROOT_ICONS = ('favicon.ico','apple-touch-icon.png')
SHARE_CARD = 'assets/og-card.png'
SHARE_ALT = 'Jacob Metoyer: research, computation and making. Cal State Long Beach computer science and physics.'

# Homepage (2026-09-29 draft 6, Shinogi): a scannable portfolio overview. Jacob on draft 5: "its my
# portfolio website why is there stories in the first place". So: every public project appears once,
# grouped by lane, each as a title plus one or two sentences of substance and a link to its write-up.
# Depth lives on the project pages. No case studies, no equipment inventory, no unpublished findings,
# no CV timeline or career pitch.
HOME_KICKER='Computer science & physics \u00b7 Cal State Long Beach'
HOME_LEDE=('I work on research data in university labs, write research software, and run my own '
    'experiments on how well AI systems do real work.')
# (section id, heading, note, ((work id, tag, summary), ...)). Each work id must exist in content.json
# and appear exactly once; the link goes to <route>#<id>.
HOME_OVERVIEW=(
    ('home-academic','Academic research','Team projects in university labs. I describe my part; the data and results stay with the labs.',(
        ('research-movement','Current',
         'Motion-capture data for gait and fall-risk research. I support participant sessions, prepare recordings for '
         'analysis, and repaired the lab\u2019s gait-analysis workflow so bad input stops it instead of producing wrong numbers.'),
        ('research-surgery','Collaboration',
         'Video-based motion tracking and sensor data for a study of the physical strain surgeons carry through long urologic operations.'),
        ('research-proteins','Joshi Laboratory \u00b7 Georgetown',
         'Standardized molecular-dynamics simulations so they could be compared, and wrote physical-plausibility checks '
         'that flag AI-generated protein structures with impossible geometry.'),
        ('research-behavior','Tsai Lab \u00b7 CSULB',
         'Scored mouse behavior from video and checked the automated tracking by hand, in a lab studying sex differences '
         'in brain and behavior.'),
    )),
    ('home-software','Public software','My own projects. Source, setup and known limits are on GitHub.',(
        ('capturesuite','Research capture',
         'Runs a multi-device research session, cameras and body-worn sensors, on one clock and seals it into a single package '
         'for quality checks and analysis. I lead its architecture: each device runs as its own plugin, so adding a sensor never touches the core.'),
        ('canvaspilot','Student tools',
         'Canvas access for students who can’t create API tokens. You sign in once with your normal school login, and a local '
         'broker makes requests without handing your session to the program asking.'),
        ('towerops','Research demo',
         'A simulated air-traffic scenario: an AI agent can suggest an action, but code checks the scenario, the approval and '
         'the readback before anything changes in the simulation. It does not connect to real aircraft.'),
        ('uma-sim','Unofficial fan software',
         'A simulator for the career mode of the game Umamusume: runs, events, races and scoring, with a browser interface.'),
    )),
    ('home-independent','Independent research','My own work, outside school and any lab. Unpublished, so I describe the questions, not the findings.',(
        ('ai-systems-research','Ongoing',
         'Experiments running AI models on real tasks: whether several models beat one, how much context a task needs, and '
         'where they fail. Every run is recorded so a result can be checked later.'),
    )),
    ('home-making','Making & interests','',(
        ('cosplay','tornadocos','Armor, props and costumes, modeled and 3D printed.'),
        ('watching-reading','TornadoZW','What I\u2019m watching, reading and playing, on MyAnimeList.'),
    )),
)

# About (2026-09-29 draft 4): the biography, in order. What he did in each place in plain words,
# not the equipment. Lab results and his unpublished personal research stay off the site.
ABOUT=(
    'I\u2019m studying computer science and physics at Cal State Long Beach, with a minor in biology. I\u2019m a BUILD Scholar, and I speak English and Spanish.',
    'My first lab was the Tsai Lab at CSULB, in 2025. The lab studies how sex differences show up in the brain and in behavior. I worked with the mice, helped with genotyping, and scored their behavior from video, going back over the automated tracking by hand.',
    'After that I spent about eight months working remotely with the Joshi Laboratory at Georgetown on protein simulations. Most of it was getting simulation data into shape and checking whether computer-generated protein structures were physically possible.',
    'Since March 2026 I\u2019ve been doing gait rehabilitation research. I help during participant sessions and get the data ready for analysis. I also fixed an analysis workflow so it stops with an error instead of giving a wrong answer, and I helped on a study of the physical strain surgery puts on surgeons.',
    'The results from all of that belong to the labs, so they aren\u2019t on this site.',
    'Outside the labs I do my own research, mostly on how people and AI systems work together and when that actually helps. I also write software, and a few of those projects are public. Most of my own research isn\u2019t published, so you\u2019ll only find the parts that are.',
    'After my degrees I\u2019m hoping to go on to an MD/PhD. The rest of the time it\u2019s cosplay, music, anime, manga and games.',
)
# Third-person bio for people who need one to paste (programs, event pages).
SHORT_BIO='Jacob Metoyer studies computer science and physics at California State University, Long Beach, with a minor in biology, and is a BUILD Scholar. He has worked in labs studying behavioral neuroscience, protein simulations and gait rehabilitation, does independent research on how people and AI systems work together, and plans to pursue an MD/PhD. He also cosplays as tornadocos.'

def safe_url(value: str) -> str:
    if not isinstance(value,str) or len(value)>600 or any(c.isspace() for c in value): raise ValueError('Invalid URL')
    u=urlsplit(value)
    if u.scheme!='https' or u.hostname not in ALLOWED_HOSTS or u.username or u.password or u.port or u.query or u.fragment: raise ValueError('URL outside approved public link set')
    return value

def validate(data: dict) -> None:
    if not isinstance(data,dict) or data.get('visibility')!='public': raise ValueError('Only explicitly public content can be built')
    if data.get('name')!='Jacob Metoyer': raise ValueError('Identity differs from approved public record')
    if set(data)!={'visibility','name','updated','identities','work'}: raise ValueError('Unexpected root field')
    if not isinstance(data['work'],list) or not isinstance(data['identities'],list): raise ValueError('Expected explicit lists')
    seen=set()
    routes={x[0] for x in NAV}
    for row in data['work']:
        if set(row)!={'id','title','category','status','route','summary','story','role','evidence','limitations','links','visibility','publication_approved'}: raise ValueError('Unexpected work field')
        story=row.get('story')
        if not isinstance(story,list) or not 1<=len(story)<=6 or any(not isinstance(p,str) or not 1<=len(p)<=2000 for p in story): raise ValueError('Invalid story')
        if row.get('visibility')!='public' or row.get('publication_approved') is not True: raise ValueError('Work entry lacks public approval')
        ident=row.get('id','')
        if not re.fullmatch(r'[a-z][a-z0-9-]{1,48}',ident) or ident in seen: raise ValueError('Invalid or duplicate work id')
        seen.add(ident)
        for key in ('title','summary','status','category','role','evidence','limitations'):
            if not isinstance(row.get(key),str) or not 1<=len(row[key])<=2000: raise ValueError(f'Invalid {key}')
        if row['category'] not in ('Research','Computing','Making'): raise ValueError('Unknown category')
        if row['route'] not in routes: raise ValueError('Invalid internal route')
        for item in row['links']:
            if set(item)!={'label','url'} or not item['label']: raise ValueError('Unexpected link field')
            safe_url(item['url'])
    for item in data['identities']:
        if set(item)!={'label','url'}: raise ValueError('Unexpected identity field')
        safe_url(item['url'])
    if not seen: raise ValueError('Empty public catalogue')

def link(url: str,label: str,cls: str='text-link') -> str:
    safe_url(url); return f'<a class="{E(cls)}" href="{E(url,quote=True)}" rel="me noopener">{E(label)} <span aria-hidden="true">↗</span></a>'

def section_intro(kicker: str,title: str,body: str='') -> str:
    return f'<header class="page-intro"><p class="eyebrow">{E(kicker)}</p><h1>{E(title)}</h1>'+ (f'<p class="intro">{E(body)}</p>' if body else '')+'</header>'

def card(row: dict,compact: bool=False) -> str:
    h='h3' if compact else 'h2'
    return f'<article class="work-card" data-category="{E(row["category"])}"><div class="card-top"><span class="category">{E(row["category"])}</span><span class="status">{E(row["status"])}</span></div><{h}><a href="{E(row["route"])}#{E(row["id"])}">{E(row["title"])}<span aria-hidden="true">↗</span></a></{h}><p>{E(row["summary"])}</p></article>'

def project_detail(row: dict) -> str:
    links=' '.join(link(x['url'],x['label']) for x in row['links'])
    story=''.join(f'<p>{E(p)}</p>' for p in row['story'])
    return f'<article id="{E(row["id"])}" class="project-detail"><div class="detail-label"><p class="eyebrow">{E(row["category"])}</p><span class="status">{E(row["status"])}</span></div><div class="detail-body"><h2>{E(row["title"])}</h2><div class="story">{story}</div><p class="scope">{E(row["limitations"])}</p><div class="project-links">{links}</div></div></article>'

ROOTED_PAGES={'404.html'}  # served by the host at arbitrary missing paths, e.g. /research/old/

def root_links(name: str,markup: str) -> str:
    """Anchor local href/src values to the site root for pages served at any depth."""
    if name not in ROOTED_PAGES: return markup
    return re.sub(r'(\s(?:href|src)=")(?![a-z][a-z0-9+.-]*:|/|#)',r'\1/',markup)

def layout(name: str,title: str,desc: str,body: str,data: dict) -> str:
    return root_links(name,page_html(name,title,desc,body,data))

def page_html(name: str,title: str,desc: str,body: str,data: dict) -> str:
    nav=''.join(f'<a href="{p}"'+(' aria-current="page"' if name==p else '')+f'>{E(t)}</a>' for p,t in NAV)
    schema={'@context':'https://schema.org','@type':'Person','name':data['name'],'url':BASE,'sameAs':[x['url'] for x in data['identities']]}
    structured=json.dumps(schema,ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e')
    canonical=BASE+'/'+('' if name=='index.html' else name)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="{CSP}"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{E(title)} · Jacob Metoyer</title><meta name="description" content="{E(desc,quote=True)}"><meta name="theme-color" content="#183c31"><meta name="referrer" content="strict-origin-when-cross-origin">
<link rel="canonical" href="{canonical}"><link rel="icon" href="assets/mark.svg" type="image/svg+xml"><link rel="icon" href="favicon.ico" sizes="48x48"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="stylesheet" href="style.css">
<meta property="og:type" content="website"><meta property="og:title" content="{E(title,quote=True)} · Jacob Metoyer"><meta property="og:description" content="{E(desc,quote=True)}"><meta property="og:url" content="{canonical}">
<meta property="og:image" content="{BASE}/{SHARE_CARD}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="{E(SHARE_ALT,quote=True)}"><meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{structured}</script><script src="site.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header class="masthead"><a class="wordmark" href="index.html" aria-label="Jacob Metoyer home">Jacob <strong>Metoyer</strong><span class="wordmark-note">research / computation / making</span></a><nav aria-label="Main navigation">{nav}</nav></header>
<main id="main">{body}</main>
<footer class="footer"><div><a class="footer-name" href="index.html">Jacob Metoyer</a><p>Research, software and making.</p></div><div class="footer-links"><a href="collaborate.html">Collaborate</a><a href="now.html">Now</a><a href="process.html">Methods &amp; evidence</a><a href="credits.html">Sources &amp; credits</a><a href="privacy.html">Privacy</a></div><div class="footer-links"><a href="https://github.com/Jacob-Met" rel="me noopener">GitHub ↗</a><a href="https://www.linkedin.com/in/jacob-metoyer-15b701352" rel="me noopener">LinkedIn ↗</a><small>Revised September 29, 2026<br>Jacob Metoyer</small></div></footer></body></html>'''

def build(out: Path,data: dict|None=None) -> dict:
    data=json.loads((ROOT/'content.json').read_text(encoding='utf-8')) if data is None else data; validate(data)
    out=out.resolve()
    if out==ROOT or ROOT.is_relative_to(out): raise ValueError('Output must not replace source')
    allowed={'index.html','work.html','research.html','ai-systems.html','computing.html','making.html','collaborate.html','about.html','process.html','now.html','credits.html','privacy.html','404.html','style.css','site.js','.nojekyll','CNAME','robots.txt','sitemap.xml','work.json','build-manifest.json','assets/mark.svg',SHARE_CARD,*ROOT_ICONS}
    if out.exists():
        for f in out.rglob('*'):
            if f.is_symlink() or (f.is_file() and f.relative_to(out).as_posix() not in allowed): raise ValueError('Output contains unexpected material; refuse to overwrite it')
    out.mkdir(parents=True,exist_ok=True); pages={}; work=data['work']
    rows={x['id']:x for x in work}
    def overview_item(ident,tag,summary):
        row=rows[ident]
        return (f'<article class="overview-item"><p class="eyebrow">{E(tag)}</p>'
                f'<h3><a href="{E(row["route"])}#{E(ident)}">{E(row["title"])}</a></h3><p>{E(summary)}</p></article>')
    def overview_section(sid,heading,note,items):
        return (f'<section class="home-section" aria-labelledby="{E(sid)}"><div class="lane-head"><h2 id="{E(sid)}">{E(heading)}</h2>'
                +(f'<p>{E(note)}</p>' if note else '')+'</div><div class="overview-grid">'+''.join(overview_item(*x) for x in items)+'</div></section>')
    home=('<header class="page-intro home-hero"><p class="eyebrow">'+E(HOME_KICKER)+'</p><h1>Jacob Metoyer</h1><p class="intro">'+E(HOME_LEDE)+'</p>'
        '<div class="actions"><a class="text-link" href="work.html">All projects \u2192</a><a class="text-link" href="about.html">About me \u2192</a></div></header>'
        +''.join(overview_section(*x) for x in HOME_OVERVIEW))
    pages['index.html']=('Research and software','Jacob Metoyer, a computer science and physics student at Cal State Long Beach: academic research in gait rehabilitation, surgical ergonomics, protein simulation and behavioral neuroscience; public research software; and independent AI-systems research.',home)
    filters='<div class="filter-wrap" hidden><div class="filters" role="group" aria-label="Filter work by field">'+''.join(f'<button type="button" data-filter="{x}" aria-pressed="{str(x=="All").lower()}">{x}</button>' for x in ['All','Research','Computing','Making'])+'</div><p id="filter-count" role="status" aria-live="polite"></p></div>'
    body=section_intro('Work','All projects.','Lab research, software, side projects and hobbies. Each card links to a longer write-up.')+filters+'<section class="work-grid catalogue" aria-label="Public work">'+''.join(card(x) for x in work)+'</section>'
    pages['work.html']=('Work','A public record of research, software, independent AI-systems experiments, and making by Jacob Metoyer.',body)
    academic=[x for x in work if x['category']=='Research' and x['id']!='ai-systems-research']
    body=section_intro('Biology / medicine / computation','Research.','Labs I’ve worked in, and what I did in each.')+'<section class="research-intro"><div><h2>Timeline.</h2><ul class="timeline"><li><strong>Jan–Sep 2025:</strong> Tsai Lab, CSULB. Mouse behavior scoring from video.</li><li><strong>Sep 2025–Apr 2026:</strong> Joshi Laboratory, Georgetown (remote). Molecular-dynamics data and structure checks.</li><li><strong>Mar 2026–now:</strong> Gait rehabilitation research. Motion capture.</li><li><strong>2026:</strong> Surgical-ergonomics collaboration. Motion tracking and sensor data.</li></ul><p>For team projects I describe my part. The results belong to the lab.</p></div><aside class="education"><p class="eyebrow">School</p><h3>California State University,<br>Long Beach</h3><p>B.S. Computer Science, B.A. Physics<br>Biology minor<br>BUILD Scholar</p><p class="small">I hope to go on to an MD/PhD.</p></aside></section>'+''.join(project_detail(x) for x in academic)
    pages['research.html']=('Research','Jacob Metoyer’s research in behavioral neuroscience, protein molecular dynamics, gait rehabilitation and surgical ergonomics.',body)
    airow=next(x for x in work if x['id']=='ai-systems-research')
    body=section_intro('Independent research','AI systems.','I run AI models on real tasks and check whether they did them well.')+project_detail(airow)+'<article class="prose"><h2>What I’m testing</h2><p>Mostly two things. Whether running more models at once actually helps, or just adds coordination overhead. And how much context a task really needs.</p><p>To keep it fair I run the same task with one model, a small group and a larger setup, and I keep the failures next to the successes.</p><h2>Next</h2><p>I want to try this with an organization: look at how a team does something now, build an AI-assisted version with ordinary tools like ChatGPT, and measure quality, time and cost. I haven’t done this for a client yet.</p></article>'
    pages['ai-systems.html']=('Independent AI systems research','Independent research by Jacob Metoyer on human–AI collaboration, agentic systems, evaluation, and reusable workflows.',body)
    body=section_intro('Software','Software.','Public projects on GitHub. Each repo has setup notes and current limits.')+''.join(project_detail(x) for x in work if x['category']=='Computing')
    pages['computing.html']=('Software','CaptureSuite, CanvasPilot, TowerOps, uma-sim, and other public computational work by Jacob Metoyer.',body)
    body=section_intro('For teams','Have a workflow worth untangling?','I build small tools and test AI-assisted workflows. If your team has a specific bottleneck in research data, document handling or a repetitive operation, I’m interested in seeing whether a focused pilot would help.')+'<article class="prose"><h2>Start with the actual problem</h2><p>Tell me what your team does now, where it gets stuck, and what a useful result would look like. I’ll suggest a narrow first step: the input, the output, the checks, and how we would tell whether the change helped. If the existing tool already does the job, I’d rather say that than build a duplicate.</p><h2>A small, testable pilot</h2><p>The first pass could use sample or redacted material. We’d agree on data handling, scope, access and terms before using real records. The deliverable would be a working example and a short account of what passed, what failed and what still needs a person.</p><h2>What you can inspect</h2><p>My <a href="computing.html">public software</a> includes CaptureSuite, a multi-device research capture project. My <a href="ai-systems.html">AI-systems page</a> explains how I compare assisted workflows without hiding failed runs. Those are examples of how I work, not case studies from your organization.</p><h2>Start a conversation</h2><p>Send me a short note on LinkedIn with the workflow, the kind of information involved (not the information itself), and what you’d want a pilot to show. Please don’t send participant data, passwords or confidential files in a first message.</p><p><a class="button" href="https://www.linkedin.com/in/jacob-metoyer-15b701352" rel="me noopener">Message me on LinkedIn ↗</a></p></article>'
    pages['collaborate.html']=('Collaborate on a focused pilot','Explore a scoped research-data, software or AI-assisted workflow pilot with Jacob Metoyer; begin with the problem and a testable first step.',body)
    body=section_intro('Cosplay / objects / stories','Making.','Cosplay, props, 3D prints, and the anime, manga and games I’m into.')+''.join(project_detail(x) for x in work if x['category']=='Making')+'<section class="culture"><p class="eyebrow">Elsewhere</p><h2>Links.</h2><p>Finished builds go on Instagram. MyAnimeList has what I’ve been watching and reading.</p><div class="actions"><a class="button" href="https://myanimelist.net/profile/TornadoZW" rel="me noopener">MyAnimeList ↗</a><a class="text-link" href="https://www.instagram.com/tornadocos/" rel="me noopener">Cosplay on Instagram ↗</a></div></section>'
    pages['making.html']=('Making & interests','Cosplay, CAD, physical making, anime, manga, and games as part of Jacob Metoyer’s broader interests.',body)
    body=section_intro('About','About me.','The longer version, in order.')+'<article class="prose">'+''.join(f'<p>{E(p)}</p>' for p in ABOUT)+'<aside class="short-bio"><p class="eyebrow">Short bio</p><p>'+E(SHORT_BIO)+'</p></aside><p><a class="text-link" href="research.html">What I did in each lab →</a></p></article>'
    pages['about.html']=('About','About Jacob Metoyer: academic research, computation, independent AI-systems research, software, and making.',body)
    body=section_intro('How I work','Methods.','How I handle data, credit and claims.')+'<article class="prose"><h2>In labs</h2><p>For team research I describe my part. The results belong to the lab. Participant data, confidential material and unpublished findings don’t go on this site.</p><h2>With AI systems</h2><p>I save the task, the tool actions, the output and the failures. A model grading its own work doesn’t count as an independent check.</p><h2>In code</h2><p>Tests, examples and known limits live in each repo. A passing test only shows that the tested thing works.</p><h2>Credit</h2><p>I use other people’s libraries and tools. Where a publication or collaboration has disclosure rules, I follow them.</p><h2>Keeping it current</h2><p>I update this site when projects change. If something here is out of date, it’s a bug.</p></article>'
    pages['process.html']=('Methods & evidence','How Jacob Metoyer approaches evidence, reproducibility, authorship, and responsibility across research, software, and independent AI-systems work.',body)
    body=section_intro('Snapshot / September 10, 2026','What I was working on.','This is a September 10 snapshot, not a live status. The Work page has the public project catalogue.')+'<div class="now-grid"><section><p class="eyebrow">Research</p><h2>Gait research.</h2><p>Motion-capture data in gait rehabilitation research. Still aiming at an MD/PhD.</p></section><section><p class="eyebrow">AI systems</p><h2>Repeatable experiments.</h2><p>Fixed tasks, saved results, and fair comparisons between one model and several.</p></section><section><p class="eyebrow">Software</p><h2>CaptureSuite.</h2><p>In active development. CanvasPilot and uma-sim are public on GitHub.</p></section><section><p class="eyebrow">Making</p><h2>Hobbies.</h2><p>Cosplay, music, anime, manga and games.</p></section></div>'
    pages['now.html']=('Now','A dated snapshot of Jacob Metoyer’s academic research, independent AI-systems experiments, software, and making.',body)
    body=section_intro('Sources & credits','Sources.','Where the descriptions on this site come from, and who owns what.')+'<article class="prose"><h2>Research</h2><p>From my CV and project records. For collaborative work I describe my part, and the labs keep their own data and results.</p><h2>AI systems</h2><p>My own project. No university, lab or client is behind it.</p><h2>Software</h2><p>Based on the public repositories, which have the licensing, install steps and current limits.</p><ul><li><a href="https://github.com/Jacob-Met/CaptureSuite">CaptureSuite source and licensing</a></li><li><a href="https://github.com/Jacob-Met/canvaspilot">CanvasPilot source and responsible-use notes</a></li><li><a href="https://github.com/Jacob-Met/TowerOps">TowerOps source and simulation limits</a></li><li><a href="https://github.com/Jacob-Met/uma-sim">uma-sim source and notice</a></li></ul><h2>Fan work</h2><p>Cosplay and uma-sim use other people’s characters and games. Those belong to their creators.</p><h2>This site</h2><p>A small static site generated from one content file, with checks that run before each build.</p></article>'
    pages['credits.html']=('Sources & credits','Source, evidence, and attribution notes for Jacob Metoyer’s public academic and technical work.',body)
    body=section_intro('Privacy','A small, static site.')+'<article class="prose"><p>This site does not include an analytics tracker, newsletter form, advertising pixel, account system, checkout, or embedded social-media feed. Its presentation assets do not require a third-party font request.</p><p>The hosting provider may process ordinary connection and request information to serve the site. Following an external link takes you to a separate service with its own privacy practices.</p><p>Do not send private research data, patient or participant information, credentials, or sensitive files through a social profile linked here. Public links are not a secure research intake channel.</p></article>'
    pages['privacy.html']=('Privacy','Privacy notes for this static personal website.',body)
    pages['404.html']=('Not found','This page is not part of the current public record.',section_intro('404','Nothing here.','That page may have moved, or the link got cut short.')+'<p class="back-home"><a class="button" href="index.html">Return home →</a></p>')
    for name,(title,desc,body) in pages.items(): (out/name).write_text(layout(name,title,desc,body,data),encoding='utf-8',newline='\n')
    for name in ['style.css','site.js']:
        (out/name).write_text((ROOT/name).read_text(encoding='utf-8'),encoding='utf-8',newline='\n')
    (out/'assets').mkdir(exist_ok=True); shutil.copyfile(ROOT/'assets'/'mark.svg',out/'assets'/'mark.svg')
    shutil.copyfile(ROOT/SHARE_CARD,out/SHARE_CARD)
    for name in ROOT_ICONS: shutil.copyfile(ROOT/'assets'/name,out/name)
    (out/'.nojekyll').write_text('',encoding='utf-8',newline='\n')
    (out/'CNAME').write_text('jacobmetoyer.com\n',encoding='utf-8',newline='\n')
    (out/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n',encoding='utf-8',newline='\n')
    sm='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}/{"" if p=="index.html" else p}</loc><lastmod>{STAMP}</lastmod></url>' for p in pages if p!='404.html')+'</urlset>'
    (out/'sitemap.xml').write_text(sm,encoding='utf-8',newline='\n')
    (out/'work.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
    manifest_files=[f for f in out.rglob('*') if f.is_file() and f.name!='build-manifest.json']
    manifest={f.relative_to(out).as_posix():hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(manifest_files,key=lambda f:f.relative_to(out).as_posix())}
    (out/'build-manifest.json').write_text(json.dumps({'schema':1,'date':STAMP,'sha256':manifest},indent=2)+'\n',encoding='utf-8',newline='\n')
    return {'pages':len(pages),'public_work_entries':len(work),'output':str(out),'files':len(manifest)+1}

if __name__=='__main__':
    p=argparse.ArgumentParser(); p.add_argument('--out',type=Path,default=ROOT.parent/'docs'); a=p.parse_args(); print(json.dumps(build(a.out),indent=2))
